export interface MedicalTopic {
  keywords: string[];
  response: string;
}

export const medicalKnowledgeBase: MedicalTopic[] = [
  // ── CARDIOLOGY ──────────────────────────────────────────────────────────────
  {
    keywords: ['heart disease', 'coronary artery disease', 'CAD', 'heart condition'],
    response: [
      '## Heart Disease (Coronary Artery Disease)',
      '',
      '### Diagnosis',
      '- ECG, stress test, echocardiogram',
      '- Coronary angiography (gold standard)',
      '- Blood tests: troponin, BNP, lipid panel',
      '',
      '### Treatment',
      '- Lifestyle: heart-healthy diet, exercise, no smoking',
      '- Medications: statins, aspirin, beta-blockers, ACE inhibitors',
      '- Procedures: angioplasty/stenting, bypass surgery (CABG)',
      '',
      '### Prevention',
      '- Control blood pressure, cholesterol, and blood sugar',
      '- Regular aerobic exercise (150 min/week)',
      '- Mediterranean diet; avoid trans fats',
      '- No smoking; limit alcohol',
      '',
      '### ⚠️ When to See a Doctor',
      '- Chest pain, pressure, or tightness',
      '- Shortness of breath at rest or with minimal exertion',
      '- Pain radiating to arm, jaw, or back',
      '',
      '*Educational information only. Consult a cardiologist for personal advice.*'
    ].join('\n')
  },
  {
    keywords: ['arrhythmia', 'irregular heartbeat', 'atrial fibrillation', 'AFib', 'palpitations', 'tachycardia', 'bradycardia'],
    response: [
      '## Arrhythmia & Irregular Heartbeat',
      '',
      '### Diagnosis',
      '- ECG/EKG: detects rhythm abnormalities',
      '- Holter monitor: 24–48 hour continuous recording',
      '- Electrophysiology study for complex arrhythmias',
      '',
      '### Treatment',
      '- Rate control: beta-blockers, calcium channel blockers',
      '- Rhythm control: antiarrhythmics (flecainide, amiodarone)',
      '- Anticoagulation (AFib): warfarin, DOACs to prevent stroke',
      '- Cardioversion (electrical or chemical)',
      '- Catheter ablation for recurrent arrhythmias',
      '- Pacemaker for bradycardia',
      '',
      '### Prevention',
      '- Manage underlying conditions (hypertension, thyroid disease)',
      '- Limit caffeine and alcohol',
      '- Maintain healthy weight',
      '- Manage stress',
      '',
      '### ⚠️ When to Seek Immediate Care',
      '- Rapid irregular heartbeat with dizziness or fainting',
      '- Chest pain with palpitations',
      '- Shortness of breath with irregular pulse',
      '',
      '*Educational information only. Consult a cardiologist.*'
    ].join('\n')
  },
  {
    keywords: ['hypertension', 'high blood pressure', 'blood pressure'],
    response: [
      '## Hypertension (High Blood Pressure)',
      '',
      '### Diagnosis',
      '- BP ≥130/80 mmHg on multiple readings',
      '- 24-hour ambulatory blood pressure monitoring',
      '- Blood tests: kidney function, electrolytes, glucose',
      '- ECG and echocardiogram for organ damage assessment',
      '',
      '### Treatment',
      '- **Lifestyle first**: DASH diet, reduce sodium (<2g/day), exercise',
      '- **Medications**: ACE inhibitors, ARBs, calcium channel blockers, diuretics',
      '- Target BP: <130/80 mmHg for most adults',
      '- Regular monitoring at home',
      '',
      '### Prevention',
      '- Maintain healthy weight (BMI <25)',
      '- Regular aerobic exercise',
      '- Low-sodium diet',
      '- Limit alcohol; no smoking',
      '- Manage stress',
      '',
      '### ⚠️ Hypertensive Crisis (>180/120)',
      '- Seek emergency care immediately',
      '- Symptoms: severe headache, vision changes, chest pain, confusion',
      '',
      '*Educational information only. Consult your doctor.*'
    ].join('\n')
  },

  // ── DERMATOLOGY ─────────────────────────────────────────────────────────────
  {
    keywords: ['acne', 'pimples', 'breakout', 'blackheads', 'whiteheads', 'cystic acne'],
    response: [
      '## Acne Vulgaris',
      '',
      '### Diagnosis',
      '- Clinical examination: comedones, papules, pustules, nodules/cysts',
      '- Graded mild/moderate/severe based on lesion count and type',
      '- Hormonal evaluation if suspected (women with irregular periods)',
      '',
      '### Treatment',
      '- **Mild**: Benzoyl peroxide, salicylic acid, topical retinoids',
      '- **Moderate**: Topical/oral antibiotics + retinoids',
      '- **Severe/Cystic**: Oral isotretinoin (Accutane); hormonal therapy for women',
      '- Avoid picking or squeezing lesions',
      '',
      '### Prevention',
      '- Gentle non-comedogenic cleanser twice daily',
      '- Non-comedogenic moisturizer and sunscreen',
      '- Avoid touching face; change pillowcases frequently',
      '- Diet: limit high-glycemic foods and dairy (some evidence)',
      '',
      '### ⚠️ When to See a Dermatologist',
      '- Severe cystic acne causing scarring',
      '- No improvement after 2–3 months of OTC treatment',
      '- Acne with signs of hormonal imbalance',
      '',
      '*Educational information only. Consult a dermatologist.*'
    ].join('\n')
  },
  {
    keywords: ['eczema', 'atopic dermatitis', 'dry itchy skin', 'skin inflammation'],
    response: [
      '## Eczema (Atopic Dermatitis)',
      '',
      '### Diagnosis',
      '- Clinical diagnosis: itchy, inflamed, dry skin in characteristic locations',
      '- Patch testing to identify contact allergens',
      '- IgE levels and allergy testing',
      '',
      '### Treatment',
      '- **Moisturize**: Apply thick emollient (ceramide-based) immediately after bathing',
      '- **Topical corticosteroids**: First-line for flares (mild to potent based on severity)',
      '- **Topical calcineurin inhibitors**: Tacrolimus, pimecrolimus (face/sensitive areas)',
      '- **Biologics**: Dupilumab (Dupixent) for moderate-severe eczema',
      '- **Antihistamines**: For itch relief (sedating at night)',
      '',
      '### Prevention & Triggers',
      '- Identify and avoid triggers (soaps, detergents, wool, sweat, stress)',
      '- Lukewarm (not hot) baths; pat dry gently',
      '- Fragrance-free products only',
      '- Keep nails short to minimize scratch damage',
      '',
      '### ⚠️ When to See a Doctor',
      '- Infected eczema (yellow crusting, weeping, fever)',
      '- Severe widespread flare not responding to treatment',
      '',
      '*Educational information only. Consult a dermatologist.*'
    ].join('\n')
  },
  {
    keywords: ['psoriasis', 'scaly skin', 'plaque psoriasis', 'psoriatic'],
    response: [
      '## Psoriasis',
      '',
      '### Diagnosis',
      '- Clinical: well-defined red plaques with silvery scales',
      '- Common sites: elbows, knees, scalp, lower back',
      '- Skin biopsy if diagnosis uncertain',
      '- Check for psoriatic arthritis (joint pain/swelling)',
      '',
      '### Treatment',
      '- **Mild**: Topical corticosteroids, vitamin D analogues (calcipotriol)',
      '- **Moderate**: Phototherapy (UVB, PUVA)',
      '- **Severe**: Methotrexate, cyclosporine, acitretin',
      '- **Biologics**: TNF inhibitors (adalimumab), IL-17 inhibitors (secukinumab)',
      '',
      '### Prevention & Management',
      '- Moisturize daily to reduce scaling',
      '- Avoid triggers: stress, infections, certain medications (beta-blockers, lithium)',
      '- Limit alcohol; no smoking',
      '- Manage associated conditions (metabolic syndrome, depression)',
      '',
      '*Educational information only. Consult a dermatologist.*'
    ].join('\n')
  },
  {
    keywords: ['skin cancer', 'melanoma', 'mole changes', 'ABCDE skin', 'basal cell carcinoma', 'squamous cell'],
    response: [
      '## Skin Cancer',
      '',
      '### Types',
      '- **Basal Cell Carcinoma (BCC)**: Most common; rarely spreads; pearly bump',
      '- **Squamous Cell Carcinoma (SCC)**: Can spread; scaly red patch or ulcer',
      '- **Melanoma**: Most dangerous; arises from pigment cells',
      '',
      '### Diagnosis — ABCDE Rule for Moles',
      '- **A**symmetry: One half unlike the other',
      '- **B**order: Irregular, ragged, or blurred edges',
      '- **C**olor: Multiple shades of brown, black, red, white, or blue',
      '- **D**iameter: Larger than 6mm (pencil eraser)',
      '- **E**volution: Any change in size, shape, color, or new symptom',
      '- Dermoscopy and biopsy for definitive diagnosis',
      '',
      '### Treatment',
      '- **BCC/SCC**: Surgical excision, Mohs surgery, cryotherapy',
      '- **Melanoma**: Wide excision, sentinel lymph node biopsy, immunotherapy, targeted therapy',
      '',
      '### Prevention',
      '- SPF 30+ sunscreen daily; reapply every 2 hours',
      '- Avoid tanning beds',
      '- Protective clothing and shade',
      '- Annual skin check with dermatologist',
      '',
      '### ⚠️ See a Dermatologist Urgently',
      '- Any mole meeting ABCDE criteria',
      '- Non-healing skin sore >2 weeks',
      '',
      '*Educational information only. Consult a dermatologist.*'
    ].join('\n')
  },

  // ── PEDIATRICS ──────────────────────────────────────────────────────────────
  {
    keywords: ['childhood illness', 'child fever', 'pediatric fever', 'fever in children', 'sick child'],
    response: [
      '## Fever in Children',
      '',
      '### Diagnosis',
      '- Temperature >38°C (100.4°F) = fever',
      '- Assess for source: ear, throat, urine, chest',
      '- Blood tests if high fever without clear source',
      '',
      '### Treatment',
      '- **Acetaminophen**: 10–15 mg/kg every 4–6 hours',
      '- **Ibuprofen** (>6 months): 5–10 mg/kg every 6–8 hours',
      '- Encourage fluids; light clothing',
      '- Do NOT use aspirin in children (Reye\'s syndrome risk)',
      '',
      '### Prevention',
      '- Frequent handwashing',
      '- Up-to-date vaccinations',
      '- Avoid contact with sick individuals',
      '',
      '### ⚠️ Seek Immediate Care',
      '- Fever in infant <3 months (any fever)',
      '- Fever >40°C (104°F)',
      '- Fever with rash, stiff neck, difficulty breathing',
      '- Seizure with fever',
      '- Child appears very ill or unresponsive',
      '',
      '*Educational information only. Consult a pediatrician.*'
    ].join('\n')
  },
  {
    keywords: ['vaccination', 'vaccine', 'immunization', 'childhood vaccine', 'vaccine schedule'],
    response: [
      '## Childhood Vaccinations',
      '',
      '### Why Vaccinate?',
      '- Prevents serious, potentially fatal diseases',
      '- Protects community through herd immunity',
      '- Safe and rigorously tested',
      '',
      '### Key Vaccine Schedule',
      '- **Birth**: Hepatitis B (dose 1)',
      '- **2 months**: DTaP, IPV, Hib, PCV13, Rotavirus',
      '- **4 months**: DTaP, IPV, Hib, PCV13, Rotavirus',
      '- **6 months**: DTaP, IPV, Hib, PCV13, Rotavirus, Hepatitis B (dose 3)',
      '- **12–15 months**: MMR, Varicella, Hepatitis A, PCV13 booster',
      '- **4–6 years**: DTaP booster, IPV booster, MMR booster, Varicella booster',
      '- **11–12 years**: Tdap, HPV series, Meningococcal',
      '',
      '### Common Side Effects (Normal)',
      '- Soreness at injection site',
      '- Low-grade fever for 1–2 days',
      '- Mild fussiness',
      '',
      '### ⚠️ Seek Care If',
      '- High fever >39°C after vaccination',
      '- Severe allergic reaction (within 15 minutes)',
      '- Prolonged crying >3 hours',
      '',
      '*Educational information only. Consult a pediatrician.*'
    ].join('\n')
  },
  {
    keywords: ['developmental milestone', 'child development', 'growth milestone', 'baby development'],
    response: [
      '## Child Developmental Milestones',
      '',
      '### Key Milestones',
      '- **2 months**: Smiles, follows objects, coos',
      '- **4 months**: Holds head steady, laughs, reaches for objects',
      '- **6 months**: Sits with support, babbles, recognizes faces',
      '- **9 months**: Sits independently, crawls, says "mama/dada"',
      '- **12 months**: Pulls to stand, first words, waves bye-bye',
      '- **18 months**: Walks independently, 10+ words, points to objects',
      '- **2 years**: Runs, 2-word phrases, follows 2-step instructions',
      '- **3 years**: Climbs stairs, 3-word sentences, plays with others',
      '',
      '### Red Flags — Consult Pediatrician',
      '- No smiling by 3 months',
      '- No babbling by 12 months',
      '- No words by 16 months',
      '- Loss of previously acquired skills at any age',
      '- No pointing or waving by 12 months',
      '',
      '*Educational information only. Consult a pediatrician.*'
    ].join('\n')
  },

  // ── SURGERY ─────────────────────────────────────────────────────────────────
  {
    keywords: ['appendicitis', 'appendix pain', 'right lower abdominal pain'],
    response: [
      '## Appendicitis',
      '',
      '### Diagnosis',
      '- Classic: pain starting around navel, moving to right lower quadrant',
      '- Rebound tenderness at McBurney\'s point',
      '- Blood tests: elevated WBC',
      '- Ultrasound (first-line); CT scan if inconclusive',
      '',
      '### Treatment',
      '- **Surgical**: Appendectomy (laparoscopic preferred)',
      '- **Antibiotics alone**: For uncomplicated appendicitis (some cases)',
      '- Emergency surgery if perforated appendix',
      '',
      '### Post-Operative Care',
      '- Light diet initially; advance as tolerated',
      '- Wound care: keep dry for 48 hours',
      '- Avoid heavy lifting for 2–4 weeks',
      '- Follow-up in 1–2 weeks',
      '',
      '### ⚠️ Emergency Signs',
      '- Sudden severe abdominal pain with rigid abdomen',
      '- High fever with abdominal pain',
      '- Vomiting with inability to pass gas',
      '',
      '*Educational information only. Consult a surgeon.*'
    ].join('\n')
  },
  {
    keywords: ['hernia', 'inguinal hernia', 'umbilical hernia', 'abdominal hernia', 'bulge abdomen'],
    response: [
      '## Hernia',
      '',
      '### Types',
      '- **Inguinal**: Groin area; most common (especially men)',
      '- **Umbilical**: Around belly button; common in infants and obese adults',
      '- **Hiatal**: Stomach pushes through diaphragm',
      '- **Incisional**: Through previous surgical scar',
      '',
      '### Diagnosis',
      '- Physical examination: visible/palpable bulge',
      '- Ultrasound or CT scan for confirmation',
      '',
      '### Treatment',
      '- **Watchful waiting**: For small, asymptomatic hernias',
      '- **Surgery**: Laparoscopic or open repair with mesh',
      '- Emergency surgery if strangulated (blood supply cut off)',
      '',
      '### ⚠️ Seek Immediate Care',
      '- Hernia becomes hard, tender, or cannot be pushed back',
      '- Nausea, vomiting with hernia pain (strangulation)',
      '',
      '*Educational information only. Consult a surgeon.*'
    ].join('\n')
  },
  {
    keywords: ['wound care', 'wound healing', 'surgical wound', 'wound infection', 'laceration'],
    response: [
      '## Wound Care & Management',
      '',
      '### Wound Assessment',
      '- Size, depth, location, contamination level',
      '- Signs of infection: redness, warmth, swelling, pus, fever',
      '- Tetanus status',
      '',
      '### Treatment',
      '- **Clean wounds**: Irrigate with saline; close with sutures/staples/glue',
      '- **Contaminated wounds**: Debridement; delayed closure; antibiotics',
      '- **Infected wounds**: Drainage, debridement, antibiotics',
      '',
      '### Home Wound Care',
      '- Keep wound clean and dry for 24–48 hours',
      '- Change dressing daily or when soiled',
      '- Apply antibiotic ointment (bacitracin)',
      '- Protect from sun to minimize scarring',
      '',
      '### ⚠️ Signs of Infection — See a Doctor',
      '- Increasing redness, warmth, or swelling',
      '- Pus or foul-smelling discharge',
      '- Fever >38°C',
      '- Red streaks spreading from wound',
      '',
      '*Educational information only. Consult a surgeon.*'
    ].join('\n')
  },

  // ── NEUROLOGY ───────────────────────────────────────────────────────────────
  {
    keywords: ['migraine', 'severe headache', 'migraine headache', 'aura headache', 'throbbing headache'],
    response: [
      '## Migraine',
      '',
      '### Diagnosis',
      '- Clinical: recurrent moderate-severe headache, often one-sided, throbbing',
      '- Associated: nausea, vomiting, light/sound sensitivity',
      '- Aura (in 25%): visual disturbances, numbness before headache',
      '- MRI to rule out secondary causes if atypical',
      '',
      '### Treatment',
      '- **Acute (abort attack)**: Triptans (sumatriptan), NSAIDs, antiemetics',
      '- **Preventive** (≥4 attacks/month): Topiramate, propranolol, amitriptyline, CGRP inhibitors',
      '- Rest in dark, quiet room; cold compress',
      '',
      '### Triggers to Avoid',
      '- Stress, irregular sleep, skipped meals',
      '- Certain foods: aged cheese, red wine, processed meats',
      '- Hormonal changes, bright lights, strong smells',
      '',
      '### ⚠️ Seek Emergency Care',
      '- "Thunderclap" headache (worst of life, sudden onset)',
      '- Headache with fever, stiff neck, rash',
      '- Headache with neurological symptoms (weakness, speech problems)',
      '',
      '*Educational information only. Consult a neurologist.*'
    ].join('\n')
  },
  {
    keywords: ['epilepsy', 'seizure', 'convulsion', 'fits', 'epileptic'],
    response: [
      '## Epilepsy & Seizures',
      '',
      '### Diagnosis',
      '- EEG: records brain electrical activity',
      '- MRI brain: identifies structural causes',
      '- Blood tests: glucose, electrolytes, toxicology',
      '- Seizure classification: focal vs. generalized',
      '',
      '### Treatment',
      '- **Antiepileptic drugs (AEDs)**: Levetiracetam, valproate, lamotrigine, carbamazepine',
      '- **Drug-resistant epilepsy**: Surgery, vagus nerve stimulation, ketogenic diet',
      '- Seizure first aid: protect from injury, do NOT restrain, time the seizure',
      '',
      '### Seizure First Aid',
      '1. Stay calm; call for help',
      '2. Clear area of hazards',
      '3. Place person on their side (recovery position)',
      '4. Do NOT put anything in mouth',
      '5. Time the seizure',
      '6. Call emergency if >5 minutes or no recovery',
      '',
      '### ⚠️ Call Emergency Services',
      '- First-ever seizure',
      '- Seizure lasting >5 minutes',
      '- No recovery of consciousness',
      '- Injury during seizure',
      '',
      '*Educational information only. Consult a neurologist.*'
    ].join('\n')
  },
  {
    keywords: ['stroke', 'brain attack', 'TIA', 'transient ischemic attack', 'FAST stroke'],
    response: [
      '## Stroke & TIA',
      '',
      '### FAST — Recognize a Stroke',
      '- **F**ace: Drooping on one side',
      '- **A**rm: Weakness or numbness (one side)',
      '- **S**peech: Slurred or unable to speak',
      '- **T**ime: Call emergency services IMMEDIATELY',
      '',
      '### Diagnosis',
      '- CT scan (emergency): Rules out hemorrhage',
      '- MRI brain: Identifies ischemic area',
      '- Blood tests, ECG, echocardiogram',
      '- Carotid ultrasound',
      '',
      '### Treatment',
      '- **Ischemic stroke**: tPA (clot-busting) within 4.5 hours; mechanical thrombectomy',
      '- **Hemorrhagic stroke**: Blood pressure control; surgery if needed',
      '- **TIA**: Antiplatelet therapy (aspirin), statins, risk factor control',
      '- Rehabilitation: physiotherapy, speech therapy, occupational therapy',
      '',
      '### Prevention',
      '- Control blood pressure, cholesterol, diabetes',
      '- No smoking; limit alcohol',
      '- Anticoagulation for AFib',
      '- Regular exercise and healthy diet',
      '',
      '*Educational information only. Call emergency services for stroke symptoms.*'
    ].join('\n')
  },
  {
    keywords: ['Parkinson', 'Parkinson\'s disease', 'tremor', 'movement disorder', 'resting tremor'],
    response: [
      '## Parkinson\'s Disease',
      '',
      '### Diagnosis',
      '- Clinical: resting tremor, rigidity, bradykinesia, postural instability',
      '- No definitive test; diagnosis is clinical',
      '- MRI to exclude other causes',
      '- DaTscan (dopamine transporter imaging)',
      '',
      '### Treatment',
      '- **Levodopa/Carbidopa**: Most effective; gold standard',
      '- **Dopamine agonists**: Pramipexole, ropinirole',
      '- **MAO-B inhibitors**: Selegiline, rasagiline',
      '- **Deep Brain Stimulation (DBS)**: For advanced disease',
      '- Physiotherapy, speech therapy, occupational therapy',
      '',
      '### Living with Parkinson\'s',
      '- Regular exercise (improves motor function)',
      '- Fall prevention strategies',
      '- Nutritional support',
      '- Support groups and mental health care',
      '',
      '*Educational information only. Consult a neurologist.*'
    ].join('\n')
  },

  // ── GENERAL PRACTICE ────────────────────────────────────────────────────────
  {
    keywords: ['cold', 'common cold', 'runny nose', 'sneezing', 'nasal congestion', 'rhinitis'],
    response: [
      '## Common Cold',
      '',
      '### Diagnosis',
      '- Clinical: runny nose, sneezing, sore throat, mild fever',
      '- Usually caused by rhinovirus',
      '- No specific test needed; throat swab if strep suspected',
      '',
      '### Treatment',
      '- **Symptomatic only** (antibiotics do NOT work for viral colds)',
      '- Decongestants (pseudoephedrine, oxymetazoline)',
      '- Antihistamines for runny nose',
      '- Saline nasal rinse',
      '- Honey + lemon for sore throat',
      '- Rest and adequate hydration',
      '',
      '### Prevention',
      '- Frequent handwashing (most effective)',
      '- Avoid touching face',
      '- Avoid close contact with sick individuals',
      '- Annual flu vaccine (prevents influenza, not cold)',
      '',
      '### ⚠️ See a Doctor If',
      '- Symptoms >10 days without improvement',
      '- High fever >39°C',
      '- Severe sore throat (possible strep)',
      '- Difficulty breathing',
      '',
      '*Educational information only. Consult your doctor.*'
    ].join('\n')
  },
  {
    keywords: ['diabetes', 'blood sugar', 'glucose', 'type 2 diabetes', 'type 1 diabetes', 'insulin', 'HbA1c'],
    response: [
      '## Diabetes Mellitus',
      '',
      '### Diagnosis',
      '- **Fasting glucose**: ≥126 mg/dL (7.0 mmol/L)',
      '- **HbA1c**: ≥6.5% (48 mmol/mol)',
      '- **Random glucose**: ≥200 mg/dL with symptoms',
      '- **OGTT**: 2-hour glucose ≥200 mg/dL',
      '',
      '### Treatment',
      '- **Type 1**: Insulin therapy (basal-bolus regimen); carb counting',
      '- **Type 2**: Metformin first-line; add SGLT2 inhibitors, GLP-1 agonists, insulin as needed',
      '- Blood glucose monitoring',
      '- HbA1c target: <7% for most adults',
      '',
      '### Prevention (Type 2)',
      '- Maintain healthy weight (5–7% weight loss reduces risk 58%)',
      '- Regular exercise (150 min/week)',
      '- Low-glycemic, high-fiber diet',
      '- Annual screening if risk factors present',
      '',
      '### ⚠️ Diabetic Emergencies',
      '- **Hypoglycemia** (<70 mg/dL): Dizziness, sweating, confusion — eat 15g fast carbs',
      '- **DKA** (Type 1): Nausea, vomiting, fruity breath — emergency care',
      '- **HHS** (Type 2): Extreme thirst, confusion — emergency care',
      '',
      '*Educational information only. Consult your doctor.*'
    ].join('\n')
  },

  // ── ANESTHESIOLOGY ──────────────────────────────────────────────────────────
  {
    keywords: ['anesthesia types', 'types of anesthesia', 'general anesthesia', 'local anesthesia', 'regional anesthesia', 'sedation types'],
    response: [
      '## Types of Anesthesia',
      '',
      '### General Anesthesia',
      '- Complete unconsciousness; used for major surgeries',
      '- Administered via IV and/or inhaled gases',
      '- Requires airway management (intubation)',
      '- Recovery: 30 min–2 hours in PACU',
      '',
      '### Regional Anesthesia',
      '- **Spinal**: Single injection into spinal fluid; lower body numbness',
      '- **Epidural**: Catheter for continuous dosing; used in labor, major surgery',
      '- **Nerve Blocks**: Targeted area numbing (arm, leg, face)',
      '',
      '### Local Anesthesia',
      '- Small area numbing for minor procedures',
      '- Lidocaine, bupivacaine most common',
      '- Patient remains fully conscious',
      '',
      '### Sedation Levels',
      '- **Minimal**: Anxiolysis; patient fully responsive',
      '- **Moderate**: Responds to verbal commands',
      '- **Deep**: Responds only to painful stimuli',
      '- **General**: Unarousable',
      '',
      '### Pre-Anesthesia Instructions',
      '- Fast 6–8 hours (solids); 2 hours (clear liquids)',
      '- Disclose all medications, allergies, prior anesthesia reactions',
      '- Arrange transportation home',
      '',
      '*Educational information only. Consult your anesthesiologist.*'
    ].join('\n')
  },
  {
    keywords: ['chronic pain', 'pain management', 'pain relief', 'pain clinic', 'neuropathic pain', 'fibromyalgia'],
    response: [
      '## Chronic Pain Management',
      '',
      '### Diagnosis',
      '- Pain lasting >3 months',
      '- Pain assessment scales (VAS 0–10, NRS)',
      '- Identify underlying cause: neuropathic, nociceptive, mixed',
      '- Imaging, nerve conduction studies as needed',
      '',
      '### Treatment Approaches',
      '- **Non-pharmacological**: Physiotherapy, CBT, acupuncture, TENS',
      '- **Medications**:',
      '  - NSAIDs/acetaminophen (mild-moderate)',
      '  - Gabapentin/pregabalin (neuropathic)',
      '  - Tricyclic antidepressants (amitriptyline)',
      '  - SNRIs (duloxetine)',
      '  - Opioids (last resort, with careful monitoring)',
      '- **Interventional**: Nerve blocks, epidural steroids, spinal cord stimulation',
      '',
      '### Fibromyalgia Specifically',
      '- Duloxetine, milnacipran, pregabalin (FDA-approved)',
      '- Aerobic exercise (most evidence-based)',
      '- CBT for pain catastrophizing',
      '- Sleep hygiene',
      '',
      '*Educational information only. Consult a pain specialist.*'
    ].join('\n')
  },

  // ── ONCOLOGY ────────────────────────────────────────────────────────────────
  {
    keywords: ['chemotherapy', 'chemo', 'cancer treatment', 'chemotherapy side effects'],
    response: [
      '## Chemotherapy',
      '',
      '### How It Works',
      '- Kills rapidly dividing cancer cells',
      '- Given in cycles to allow recovery',
      '- Can be curative, adjuvant (after surgery), or palliative',
      '',
      '### Common Side Effects',
      '- Nausea and vomiting (managed with antiemetics)',
      '- Hair loss (alopecia) — usually temporary',
      '- Fatigue',
      '- Increased infection risk (low WBC)',
      '- Mouth sores (mucositis)',
      '- Peripheral neuropathy (tingling/numbness)',
      '',
      '### Managing Side Effects',
      '- Antiemetics before and after chemo',
      '- G-CSF injections to boost WBC',
      '- Good oral hygiene for mucositis',
      '- Rest and gentle exercise for fatigue',
      '- High-protein, high-calorie diet',
      '',
      '### ⚠️ Seek Immediate Care During Chemo',
      '- Fever >38°C (neutropenic fever — emergency)',
      '- Severe vomiting preventing fluid intake',
      '- Unusual bleeding or bruising',
      '- Chest pain or difficulty breathing',
      '',
      '*Educational information only. Consult your oncologist.*'
    ].join('\n')
  },
  {
    keywords: ['immunotherapy', 'cancer immunotherapy', 'checkpoint inhibitor', 'targeted therapy', 'cancer targeted'],
    response: [
      '## Immunotherapy & Targeted Cancer Therapy',
      '',
      '### Immunotherapy',
      '- **Checkpoint Inhibitors**: Pembrolizumab, nivolumab — remove brakes on immune system',
      '- **CAR-T Cell Therapy**: Engineered T-cells attack cancer',
      '- **Cancer Vaccines**: Sipuleucel-T (prostate cancer)',
      '- Side effects: immune-related (colitis, pneumonitis, thyroiditis)',
      '',
      '### Targeted Therapy',
      '- Attacks specific cancer mutations/proteins',
      '- Examples: Imatinib (CML), trastuzumab (HER2+ breast), erlotinib (EGFR+ lung)',
      '- Requires biomarker testing before use',
      '- Generally better tolerated than chemotherapy',
      '',
      '### Hormone Therapy',
      '- **Breast cancer**: Tamoxifen, aromatase inhibitors (letrozole)',
      '- **Prostate cancer**: Enzalutamide, abiraterone, LHRH agonists',
      '',
      '### ⚠️ Immune-Related Side Effects',
      '- Diarrhea/colitis: Report immediately',
      '- Shortness of breath (pneumonitis)',
      '- Skin rash',
      '- Fatigue and joint pain',
      '',
      '*Educational information only. Consult your oncologist.*'
    ].join('\n')
  },

  // ── GYNECOLOGY ──────────────────────────────────────────────────────────────
  {
    keywords: ['PCOS', 'polycystic ovary syndrome', 'irregular periods PCOS', 'ovarian cysts hormones'],
    response: [
      '## Polycystic Ovary Syndrome (PCOS)',
      '',
      '### Diagnosis (Rotterdam Criteria — 2 of 3)',
      '- Irregular or absent periods',
      '- Elevated androgens (blood test or clinical signs: acne, hirsutism)',
      '- Polycystic ovaries on ultrasound',
      '- Exclude other causes (thyroid, prolactin, adrenal)',
      '',
      '### Treatment',
      '- **Menstrual regulation**: Combined oral contraceptive pill',
      '- **Insulin resistance**: Metformin',
      '- **Fertility**: Clomiphene, letrozole, IVF',
      '- **Hirsutism/Acne**: Anti-androgens (spironolactone)',
      '- **Lifestyle**: Weight loss (5–10%) significantly improves symptoms',
      '',
      '### Long-term Risks',
      '- Type 2 diabetes (screen regularly)',
      '- Endometrial cancer (irregular periods → unopposed estrogen)',
      '- Cardiovascular disease',
      '- Depression and anxiety',
      '',
      '*Educational information only. Consult a gynecologist.*'
    ].join('\n')
  },
  {
    keywords: ['endometriosis', 'painful periods', 'dysmenorrhea severe', 'pelvic pain endometriosis'],
    response: [
      '## Endometriosis',
      '',
      '### Diagnosis',
      '- Clinical: severe dysmenorrhea, pelvic pain, painful intercourse, infertility',
      '- Transvaginal ultrasound (endometriomas)',
      '- **Definitive**: Laparoscopy with biopsy',
      '',
      '### Treatment',
      '- **Pain management**: NSAIDs, combined OCP, progestins',
      '- **Hormonal suppression**: GnRH agonists (leuprolide), dienogest',
      '- **Surgery**: Laparoscopic excision of lesions',
      '- **Fertility**: IVF if needed',
      '',
      '### Living with Endometriosis',
      '- Heat therapy for pain relief',
      '- Anti-inflammatory diet',
      '- Pelvic floor physiotherapy',
      '- Mental health support',
      '',
      '### ⚠️ See a Doctor',
      '- Severe pelvic pain not responding to OTC pain relief',
      '- Difficulty conceiving',
      '- Pain with bowel movements or urination',
      '',
      '*Educational information only. Consult a gynecologist.*'
    ].join('\n')
  },
  {
    keywords: ['menopause', 'perimenopause', 'hot flashes', 'night sweats menopause', 'hormone replacement'],
    response: [
      '## Menopause & Perimenopause',
      '',
      '### Diagnosis',
      '- Menopause: 12 consecutive months without period (average age 51)',
      '- Perimenopause: irregular periods + symptoms (can last 4–10 years)',
      '- FSH >30 IU/L, low estradiol',
      '',
      '### Symptoms',
      '- Hot flashes and night sweats',
      '- Vaginal dryness and discomfort',
      '- Sleep disturbances',
      '- Mood changes, anxiety, depression',
      '- Cognitive changes ("brain fog")',
      '- Bone loss (osteoporosis risk)',
      '',
      '### Treatment',
      '- **HRT (Hormone Replacement Therapy)**: Most effective for hot flashes; discuss risks/benefits',
      '- **Non-hormonal**: SSRIs/SNRIs, gabapentin for hot flashes',
      '- **Vaginal estrogen**: For local symptoms (low systemic absorption)',
      '- **Bone protection**: Calcium, vitamin D, bisphosphonates if osteoporosis',
      '',
      '### Prevention',
      '- Weight-bearing exercise (bone health)',
      '- Calcium 1200mg/day + Vitamin D 800–1000 IU/day',
      '- Regular DEXA scan from age 65 (or earlier if risk factors)',
      '',
      '*Educational information only. Consult a gynecologist.*'
    ].join('\n')
  },
  {
    keywords: ['pregnancy', 'prenatal', 'antenatal', 'pregnant', 'first trimester', 'second trimester', 'third trimester'],
    response: [
      '## Pregnancy & Prenatal Care',
      '',
      '### First Trimester (Weeks 1–12)',
      '- Confirm pregnancy; dating ultrasound (8–12 weeks)',
      '- Blood tests: blood type, CBC, rubella, HIV, STIs',
      '- Genetic screening: NIPT, nuchal translucency',
      '- Start folic acid 400–800 mcg/day',
      '- Avoid alcohol, smoking, raw fish, unpasteurized foods',
      '',
      '### Second Trimester (Weeks 13–26)',
      '- Anatomy scan (18–20 weeks)',
      '- Glucose tolerance test (24–28 weeks)',
      '- Quad screen (15–20 weeks)',
      '- Iron supplementation if anemic',
      '',
      '### Third Trimester (Weeks 27–40)',
      '- Group B Strep screening (35–37 weeks)',
      '- Fetal movement monitoring',
      '- Birth plan discussion',
      '- Whooping cough (Tdap) vaccine',
      '',
      '### ⚠️ Seek Immediate Care',
      '- Vaginal bleeding at any stage',
      '- Severe abdominal pain',
      '- Decreased fetal movement',
      '- Signs of preeclampsia: severe headache, vision changes, swelling',
      '- Rupture of membranes',
      '',
      '*Educational information only. Consult your OB/GYN.*'
    ].join('\n')
  },

  // ── RADIOLOGY ───────────────────────────────────────────────────────────────
  {
    keywords: ['MRI scan', 'MRI imaging', 'magnetic resonance imaging', 'MRI preparation'],
    response: [
      '## MRI (Magnetic Resonance Imaging)',
      '',
      '### What It Shows',
      '- Excellent soft tissue detail: brain, spine, joints, organs',
      '- No ionizing radiation',
      '- Best for: brain tumors, MS, disc herniation, ligament tears, stroke',
      '',
      '### Preparation',
      '- Remove all metal objects (jewelry, piercings)',
      '- Inform radiologist of: pacemaker, metal implants, cochlear implants',
      '- Contrast (gadolinium): inform of kidney disease or allergies',
      '- Claustrophobia: discuss sedation options',
      '- Fasting: usually not required (unless abdominal MRI)',
      '',
      '### During the Scan',
      '- Loud knocking noises — earplugs provided',
      '- Must remain still (20–60 minutes)',
      '- Open MRI available for severe claustrophobia',
      '',
      '### Safety',
      '- Safe in pregnancy (second/third trimester); avoid contrast',
      '- No radiation exposure',
      '- Gadolinium contrast: avoid if GFR <30 (NSF risk)',
      '',
      '*Educational information only. Consult your radiologist.*'
    ].join('\n')
  },
  {
    keywords: ['CT scan', 'computed tomography', 'CAT scan', 'CT preparation', 'CT contrast'],
    response: [
      '## CT Scan (Computed Tomography)',
      '',
      '### What It Shows',
      '- Detailed cross-sectional images of body',
      '- Excellent for: trauma, chest, abdomen, pelvis, bones',
      '- Fast (minutes); available 24/7 in emergencies',
      '',
      '### Common Uses',
      '- **Head CT**: Stroke, bleeding, trauma, headache',
      '- **Chest CT**: Pulmonary embolism, pneumonia, lung nodules',
      '- **Abdominal CT**: Appendicitis, kidney stones, masses',
      '- **CT Angiography**: Blood vessel disease',
      '',
      '### Preparation',
      '- Oral contrast: drink 1–2 hours before (abdominal CT)',
      '- IV contrast: inform of allergies, kidney function',
      '- Remove metal objects',
      '- Fasting 4 hours if IV contrast used',
      '',
      '### Radiation',
      '- Moderate dose (2–20 mSv)',
      '- Benefits usually outweigh risks',
      '- Avoid in pregnancy if possible; use ultrasound/MRI instead',
      '',
      '*Educational information only. Consult your radiologist.*'
    ].join('\n')
  },
  {
    keywords: ['X-ray', 'xray', 'chest X-ray', 'bone X-ray', 'radiograph'],
    response: [
      '## X-Ray (Radiograph)',
      '',
      '### What It Shows',
      '- **Chest X-ray**: Pneumonia, heart size, rib fractures, lung masses, pleural effusion',
      '- **Bone X-ray**: Fractures, dislocations, arthritis, bone tumors',
      '- **Abdominal X-ray**: Bowel obstruction, free air, kidney stones',
      '',
      '### Preparation',
      '- Remove jewelry and metal objects in the area',
      '- Wear comfortable clothing',
      '- Inform radiographer if pregnant',
      '',
      '### Radiation',
      '- Very low dose (~0.1 mSv for chest X-ray)',
      '- Equivalent to ~10 days of natural background radiation',
      '- Lead apron for reproductive organs when appropriate',
      '',
      '### Limitations',
      '- Limited soft tissue detail (MRI/CT better)',
      '- 2D image only',
      '- Some fractures not visible on X-ray (MRI needed)',
      '',
      '*Educational information only. Consult your radiologist.*'
    ].join('\n')
  },

  // ── EXISTING TOPICS (preserved) ─────────────────────────────────────────────
  {
    keywords: ['headache', 'head pain', 'tension headache', 'cluster headache'],
    response: [
      '## Headache',
      '',
      '### Diagnosis',
      '- **Tension**: Band-like pressure, bilateral, mild-moderate',
      '- **Migraine**: Throbbing, unilateral, with nausea/light sensitivity',
      '- **Cluster**: Severe, one-sided, around eye, with tearing',
      '- Red flags: sudden onset, fever, neurological symptoms → imaging needed',
      '',
      '### Treatment',
      '- **Tension**: OTC analgesics (ibuprofen, acetaminophen), stress management',
      '- **Migraine**: Triptans, NSAIDs, antiemetics; preventives if frequent',
      '- **Cluster**: Oxygen therapy, sumatriptan injection, verapamil (prevention)',
      '',
      '### Prevention',
      '- Regular sleep schedule',
      '- Stay hydrated',
      '- Manage stress',
      '- Identify and avoid triggers',
      '',
      '### ⚠️ Emergency Signs',
      '- Sudden "thunderclap" headache',
      '- Headache with fever and stiff neck',
      '- Headache with neurological symptoms',
      '',
      '*Educational information only. Consult a neurologist.*'
    ].join('\n')
  },
  {
    keywords: ['anxiety', 'anxiety disorder', 'panic attack', 'worry', 'anxious'],
    response: [
      '## Anxiety Disorders',
      '',
      '### Diagnosis',
      '- GAD: excessive worry >6 months affecting daily life',
      '- Panic disorder: recurrent unexpected panic attacks',
      '- Social anxiety, specific phobias, PTSD',
      '- Rule out medical causes (thyroid, cardiac)',
      '',
      '### Treatment',
      '- **First-line**: CBT (cognitive behavioral therapy)',
      '- **Medications**: SSRIs (sertraline, escitalopram), SNRIs',
      '- **Acute panic**: Benzodiazepines (short-term only)',
      '- Mindfulness, relaxation techniques, exercise',
      '',
      '### Self-Help Strategies',
      '- Diaphragmatic breathing (4-7-8 technique)',
      '- Regular aerobic exercise',
      '- Limit caffeine and alcohol',
      '- Adequate sleep',
      '',
      '*Educational information only. Consult a mental health professional.*'
    ].join('\n')
  },
  {
    keywords: ['depression', 'depressed', 'low mood', 'sadness persistent', 'major depression'],
    response: [
      '## Depression',
      '',
      '### Diagnosis',
      '- PHQ-9 screening tool',
      '- Symptoms ≥2 weeks: low mood, anhedonia, fatigue, sleep/appetite changes',
      '- Rule out medical causes (thyroid, anemia)',
      '',
      '### Treatment',
      '- **Mild**: Psychotherapy (CBT), exercise, lifestyle changes',
      '- **Moderate-Severe**: SSRIs (sertraline, fluoxetine) + psychotherapy',
      '- **Treatment-resistant**: SNRIs, bupropion, augmentation, ECT',
      '- Response expected in 4–6 weeks',
      '',
      '### Self-Care',
      '- Regular exercise (as effective as medication for mild depression)',
      '- Social connection',
      '- Sleep hygiene',
      '- Limit alcohol',
      '',
      '### ⚠️ Seek Immediate Help',
      '- Thoughts of self-harm or suicide',
      '- Crisis line: 988 (US) or local emergency services',
      '',
      '*Educational information only. Consult a mental health professional.*'
    ].join('\n')
  },
  {
    keywords: ['asthma', 'wheezing', 'bronchospasm', 'inhaler', 'shortness of breath asthma'],
    response: [
      '## Asthma',
      '',
      '### Diagnosis',
      '- Spirometry: reversible airflow obstruction (FEV1 improves >12% with bronchodilator)',
      '- Peak flow monitoring',
      '- Allergy testing',
      '',
      '### Treatment',
      '- **Reliever (rescue)**: SABA (salbutamol/albuterol) — use when symptomatic',
      '- **Controller**: Inhaled corticosteroids (ICS) — daily use',
      '- **Step-up**: ICS + LABA (formoterol), leukotriene modifiers',
      '- **Biologics**: Omalizumab, mepolizumab for severe allergic/eosinophilic asthma',
      '',
      '### Asthma Action Plan',
      '- Green zone (>80% peak flow): Continue regular medications',
      '- Yellow zone (50–80%): Increase reliever; contact doctor',
      '- Red zone (<50%): Emergency — use reliever; seek immediate care',
      '',
      '### ⚠️ Severe Asthma Attack',
      '- Unable to speak in full sentences',
      '- Lips or fingernails turning blue',
      '- No improvement with reliever inhaler',
      '- Call emergency services',
      '',
      '*Educational information only. Consult a pulmonologist or GP.*'
    ].join('\n')
  },
  {
    keywords: ['back pain', 'lower back pain', 'lumbar pain', 'sciatica', 'disc herniation'],
    response: [
      '## Back Pain',
      '',
      '### Diagnosis',
      '- Most (90%) is non-specific musculoskeletal',
      '- Red flags: trauma, cancer history, fever, neurological symptoms → imaging',
      '- MRI for suspected disc herniation or nerve compression',
      '',
      '### Treatment',
      '- **Acute (<6 weeks)**: Stay active; NSAIDs; heat/ice; physiotherapy',
      '- **Chronic (>12 weeks)**: Physiotherapy, CBT, exercise programs',
      '- **Sciatica**: NSAIDs, physiotherapy; epidural steroid injection if severe',
      '- **Surgery**: Only for specific indications (cauda equina, failed conservative)',
      '',
      '### Prevention',
      '- Core strengthening exercises',
      '- Proper lifting technique (bend knees, not back)',
      '- Ergonomic workstation setup',
      '- Maintain healthy weight',
      '',
      '*Educational information only. Consult a doctor or physiotherapist.*'
    ].join('\n')
  },
  {
    keywords: ['sleep', 'insomnia', 'sleep problems', 'sleep disorder', 'poor sleep'],
    response: [
      '## Sleep Disorders & Insomnia',
      '',
      '### Diagnosis',
      '- Insomnia: difficulty falling/staying asleep ≥3 nights/week for ≥3 months',
      '- Sleep study (polysomnography) for sleep apnea',
      '- Epworth Sleepiness Scale for daytime sleepiness',
      '',
      '### Treatment',
      '- **CBT-I**: First-line for chronic insomnia (more effective than medication)',
      '- **Sleep hygiene**: Consistent schedule, dark/cool room, no screens 1 hour before bed',
      '- **Medications**: Melatonin (short-term), zolpidem (short-term), doxepin',
      '- **Sleep apnea**: CPAP therapy; weight loss; positional therapy',
      '',
      '### Sleep Hygiene Tips',
      '- Same wake time every day (including weekends)',
      '- Avoid caffeine after 2pm',
      '- No alcohol within 3 hours of bedtime',
      '- Exercise regularly (not within 2 hours of bedtime)',
      '',
      '*Educational information only. Consult a sleep specialist.*'
    ].join('\n')
  },
  {
    keywords: ['nutrition', 'diet', 'healthy eating', 'balanced diet', 'nutrients'],
    response: [
      '## Nutrition & Healthy Eating',
      '',
      '### Key Principles',
      '- **Variety**: Eat from all food groups',
      '- **Balance**: Appropriate portions',
      '- **Moderation**: Limit processed foods, sugar, saturated fats',
      '',
      '### Recommended Daily Intake',
      '- Fruits & vegetables: 5+ servings/day',
      '- Whole grains: 3+ servings/day',
      '- Protein: 0.8g/kg body weight (lean meats, fish, legumes)',
      '- Dairy/alternatives: 2–3 servings/day',
      '- Water: 8 glasses (2L)/day',
      '',
      '### Evidence-Based Diets',
      '- **Mediterranean**: Best evidence for cardiovascular health',
      '- **DASH**: Proven for blood pressure reduction',
      '- **Plant-based**: Reduces chronic disease risk',
      '',
      '*Educational information only. Consult a registered dietitian.*'
    ].join('\n')
  },
  {
    keywords: ['fever', 'high temperature', 'pyrexia', 'temperature'],
    response: [
      '## Fever',
      '',
      '### Diagnosis',
      '- Temperature >38°C (100.4°F) = fever',
      '- Assess for source: infection, inflammation, medication',
      '- Blood tests, urine culture, chest X-ray as indicated',
      '',
      '### Treatment',
      '- **Antipyretics**: Acetaminophen (paracetamol) or ibuprofen',
      '- Adequate hydration',
      '- Rest; light clothing',
      '- Treat underlying cause',
      '',
      '### ⚠️ Seek Immediate Care',
      '- Fever >40°C (104°F)',
      '- Fever in infant <3 months',
      '- Fever with stiff neck, rash, confusion',
      '- Fever with difficulty breathing',
      '- Fever lasting >3 days',
      '',
      '*Educational information only. Consult your doctor.*'
    ].join('\n')
  },
  {
    keywords: ['allergy', 'allergic reaction', 'anaphylaxis', 'food allergy', 'hay fever'],
    response: [
      '## Allergies & Allergic Reactions',
      '',
      '### Diagnosis',
      '- Skin prick test or intradermal test',
      '- Specific IgE blood tests (RAST)',
      '- Oral food challenge (gold standard for food allergy)',
      '',
      '### Treatment',
      '- **Mild (hay fever)**: Antihistamines, nasal corticosteroids',
      '- **Moderate**: Allergen avoidance; immunotherapy (allergy shots)',
      '- **Anaphylaxis**: Epinephrine (EpiPen) IMMEDIATELY; call emergency services',
      '',
      '### Anaphylaxis Action',
      '1. Inject epinephrine (outer thigh)',
      '2. Call emergency services (911)',
      '3. Lie flat with legs elevated',
      '4. Second epinephrine dose after 5–15 minutes if needed',
      '',
      '### ⚠️ Signs of Anaphylaxis',
      '- Throat swelling, difficulty breathing',
      '- Rapid pulse, dizziness, loss of consciousness',
      '- Widespread hives with above symptoms',
      '',
      '*Educational information only. Consult an allergist.*'
    ].join('\n')
  }
];
