/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Allergy {
  'name' : string,
  'severity' : string,
  'reaction' : string,
}
export type BloodType = { 'aNegative' : null } |
  { 'oPositive' : null } |
  { 'abPositive' : null } |
  { 'bPositive' : null } |
  { 'aPositive' : null } |
  { 'oNegative' : null } |
  { 'abNegative' : null } |
  { 'bNegative' : null };
export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface MLInput {
  'age' : number,
  'bmi' : number,
  'sleepQuality' : string,
  'saltIntake' : string,
  'stressLevel' : string,
  'bloodPressure' : number,
  'exerciseFrequency' : number,
  'heartRate' : number,
  'gender' : string,
  'smokingStatus' : string,
  'medicationAdherence' : string,
  'diabetesStatus' : string,
  'cholesterol' : number,
}
export interface MLPrediction {
  'featureWeights' : Array<[string, number]>,
  'modelVersion' : string,
  'timestamp' : bigint,
  'confidence' : number,
  'riskLevel' : string,
}
export interface UserProfile {
  'bio' : [] | [string],
  'bloodType' : [] | [BloodType],
  'dateOfBirth' : [] | [bigint],
  'name' : string,
  'emergencyContact' : [] | [EmergencyContact],
  'email' : [] | [string],
  'website' : [] | [string],
  'company' : [] | [string],
  'image' : [] | [string],
  'allergies' : Array<Allergy>,
  'location' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMedicalFile' : ActorMethod<[string], boolean>,
  'getAllPredictions' : ActorMethod<[], Array<[Principal, MLPrediction]>>,
  'getCallerMLPrediction' : ActorMethod<[], [] | [MLPrediction]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeatureImportance' : ActorMethod<[], Array<[string, number]>>,
  'getLocation' : ActorMethod<[], [] | [string]>,
  'getMedicalFile' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getUserMLPrediction' : ActorMethod<[Principal], [] | [MLPrediction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMedicalFiles' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'runMLPrediction' : ActorMethod<[MLInput], MLPrediction>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLocation' : ActorMethod<[string], undefined>,
  'uploadMedicalFile' : ActorMethod<[string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];