/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MLPrediction = IDL.Record({
  'featureWeights' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
  'modelVersion' : IDL.Text,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Nat8,
  'riskLevel' : IDL.Text,
});
export const BloodType = IDL.Variant({
  'aNegative' : IDL.Null,
  'oPositive' : IDL.Null,
  'abPositive' : IDL.Null,
  'bPositive' : IDL.Null,
  'aPositive' : IDL.Null,
  'oNegative' : IDL.Null,
  'abNegative' : IDL.Null,
  'bNegative' : IDL.Null,
});
export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Allergy = IDL.Record({
  'name' : IDL.Text,
  'severity' : IDL.Text,
  'reaction' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'bloodType' : IDL.Opt(BloodType),
  'dateOfBirth' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'emergencyContact' : IDL.Opt(EmergencyContact),
  'email' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(IDL.Text),
  'allergies' : IDL.Vec(Allergy),
  'location' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const MedicalFileMetadata = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Opt(IDL.Text),
  'size' : IDL.Nat,
  'filename' : IDL.Text,
  'uploadedAt' : Time,
});
export const MLInput = IDL.Record({
  'age' : IDL.Nat8,
  'bmi' : IDL.Nat8,
  'sleepQuality' : IDL.Text,
  'saltIntake' : IDL.Text,
  'stressLevel' : IDL.Text,
  'bloodPressure' : IDL.Nat8,
  'exerciseFrequency' : IDL.Nat8,
  'heartRate' : IDL.Nat8,
  'gender' : IDL.Text,
  'smokingStatus' : IDL.Text,
  'medicationAdherence' : IDL.Text,
  'diabetesStatus' : IDL.Text,
  'cholesterol' : IDL.Nat8,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMedicalFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllPredictions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, MLPrediction))],
      ['query'],
    ),
  'getCallerMLPrediction' : IDL.Func([], [IDL.Opt(MLPrediction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeatureImportance' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8))],
      ['query'],
    ),
  'getLocation' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMedicalFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getMedicalFileMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MedicalFileMetadata)],
      ['query'],
    ),
  'getMedicalReportMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MedicalFileMetadata)],
      ['query'],
    ),
  'getMedicalReportsSummary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, MedicalFileMetadata))],
      ['query'],
    ),
  'getUserMLPrediction' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MLPrediction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMedicalFiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'listMedicalFilesMetadata' : IDL.Func(
      [],
      [IDL.Vec(MedicalFileMetadata)],
      ['query'],
    ),
  'runMLPrediction' : IDL.Func([MLInput], [MLPrediction], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLocation' : IDL.Func([IDL.Text], [], []),
  'uploadMedicalFile' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MLPrediction = IDL.Record({
    'featureWeights' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8)),
    'modelVersion' : IDL.Text,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Nat8,
    'riskLevel' : IDL.Text,
  });
  const BloodType = IDL.Variant({
    'aNegative' : IDL.Null,
    'oPositive' : IDL.Null,
    'abPositive' : IDL.Null,
    'bPositive' : IDL.Null,
    'aPositive' : IDL.Null,
    'oNegative' : IDL.Null,
    'abNegative' : IDL.Null,
    'bNegative' : IDL.Null,
  });
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Allergy = IDL.Record({
    'name' : IDL.Text,
    'severity' : IDL.Text,
    'reaction' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'bloodType' : IDL.Opt(BloodType),
    'dateOfBirth' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'emergencyContact' : IDL.Opt(EmergencyContact),
    'email' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
    'allergies' : IDL.Vec(Allergy),
    'location' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const MedicalFileMetadata = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Opt(IDL.Text),
    'size' : IDL.Nat,
    'filename' : IDL.Text,
    'uploadedAt' : Time,
  });
  const MLInput = IDL.Record({
    'age' : IDL.Nat8,
    'bmi' : IDL.Nat8,
    'sleepQuality' : IDL.Text,
    'saltIntake' : IDL.Text,
    'stressLevel' : IDL.Text,
    'bloodPressure' : IDL.Nat8,
    'exerciseFrequency' : IDL.Nat8,
    'heartRate' : IDL.Nat8,
    'gender' : IDL.Text,
    'smokingStatus' : IDL.Text,
    'medicationAdherence' : IDL.Text,
    'diabetesStatus' : IDL.Text,
    'cholesterol' : IDL.Nat8,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMedicalFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllPredictions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, MLPrediction))],
        ['query'],
      ),
    'getCallerMLPrediction' : IDL.Func([], [IDL.Opt(MLPrediction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeatureImportance' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat8))],
        ['query'],
      ),
    'getLocation' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMedicalFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getMedicalFileMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MedicalFileMetadata)],
        ['query'],
      ),
    'getMedicalReportMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MedicalFileMetadata)],
        ['query'],
      ),
    'getMedicalReportsSummary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, MedicalFileMetadata))],
        ['query'],
      ),
    'getUserMLPrediction' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MLPrediction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMedicalFiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'listMedicalFilesMetadata' : IDL.Func(
        [],
        [IDL.Vec(MedicalFileMetadata)],
        ['query'],
      ),
    'runMLPrediction' : IDL.Func([MLInput], [MLPrediction], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLocation' : IDL.Func([IDL.Text], [], []),
    'uploadMedicalFile' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };